import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Admin User',
      email: 'admin@statsurgicalsupply.com',
      password: bcrypt.hashSync('Statsurgicalsupply1*'),
      isAdmin: true,
    },
    {
      name: 'Sebastian',
      email: 'admin@surgicalsc.com',
      password: bcrypt.hashSync('Statsurgicalsupply1*'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Medtronic name 1',
      manufacturer: 'MEDTRONIC',
      slug: 'MEDTRONIC7510400',
      lot: 'WE1',
      expiration: '2022-01-01',
      image: '/images/7510400-WE1.png',
      reference: '7510400',
      description: 'Bone Graft Kit, Medium Size',
      descriptionBulk: 'Bulk description',
      price: 4240,
      priceBulk: 4000,
      each: 'Each',
      bulk: 'Bulk',
      countInStock: 10,
      countInStockBulk: 10,
      notes: 'notes',
      includes:
        '2) Vials of Sterile rhBMP-2 (4.2 mg), (1) Package of 4 Sterile Absorbable Collagen Sponges (ACS) 1 x 2 in., (2) Vials of Sterile Water for Injection (5 mL), (4) Sterile 5 mL Syringes with 20G 1.5 in. Needle',
    },
    {
      name: 'Medtronic 7510200',
      manufacturer: 'MEDTRONIC',
      slug: 'MEDTRONIC7510200',
      lot: 'WE1',
      expiration: '2022-01-01',
      image: '/images/7510200-WE1.png',
      reference: '7510200',
      description: 'Bone Graft Kit, Medium Size',
      descriptionBulk: 'Bulk description',
      price: 4240,
      priceBulk: 4000,
      each: 'Each',
      bulk: 'Bulk',
      countInStock: 10,
      countInStockBulk: 10,
      notes: 'notes',
      includes:
        '(1) Vial of Sterile rhBMP-2 (4.2 mg), (1) Package of 2 Sterile Absorbable Collagen Sponge (ACS) 1 x 2 in., (1) Vial of Sterile Water for Injection (5 mL), (2) Sterile 5 mL Syringes with 20G 1.5 in. Needle',
    },

    {
      name: 'Medtronic2',
      manufacturer: 'MEDTRONIC',
      slug: 'MEDTRONIC7510600',
      lot: 'WE1',
      expiration: '2022-01-01',
      image: '/images/7510600-WE1.png',
      reference: '7510600',
      description: 'Bone Graft Kit, Medium Size',
      descriptionBulk: 'Bulk description',
      price: 4240,
      priceBulk: 4000,
      each: 'Each',
      bulk: 'Bulk',
      countInStock: 10,
      countInStockBulk: 10,
      notes: 'notes',
      includes:
        '(1) Vial of Sterile rhBMP-2 (12 mg), (1) Package of 6 Sterile Absorbable Collagen Sponge (ACS) 1 x 2 in., (1) Vial of Sterile Water for Injection (10 mL), (2) Sterile 10 mL Syringes with 20G 1.5 in. Needle',
    },

    {
      name: 'Medtronic 7510800',
      manufacturer: 'COVIDIEN ENERGY',
      slug: 'COVIDIENENERGYLF1837',
      lot: 'WE1',
      expiration: '2022-01-01',
      image: '/images/LF1837-WE1.png',
      reference: 'LF1837',
      description: 'Bone Graft Kit, Medium Size',
      descriptionBulk: 'Bulk description',
      price: 4240,
      priceBulk: 4000,
      each: 'Each',
      bulk: 'Bulk',
      countInStock: 10,
      countInStockBulk: 10,
      notes: 'notes',
      includes: '1) Sealer/Divider',
    },

    {
      name: 'Medtronic 7510800',
      manufacturer: 'STRYKER',
      slug: 'STRYKER5820-107-530C',
      lot: 'WE1',
      expiration: '2022-01-01',
      image: '/images/5820-107-530C-WE1.png',
      reference: '5820-107-530C',
      description: 'Bone Graft Kit, Medium Size',
      descriptionBulk: 'Bulk description',
      price: 4240,
      priceBulk: 4000,
      each: 'Each',
      bulk: 'Bulk',
      countInStock: 10,
      countInStockBulk: 10,
      notes: 'notes',
      includes: '1) Sealer/Divider',
    },
    {
      name: 'ARTHREX AR-2922D-24-3',
      manufacturer: 'ARTHREX',
      slug: 'AR-2922D-24-3',
      lot: '10762361',
      expiration: '2025-02-28',
      image: '/images/5820-107-530C-WE1.png',
      reference: '5820-107-530C',
      description: 'Bone Graft Kit, Medium Size',
      descriptionBulk: 'Bulk description',
      price: 4240,
      priceBulk: 4000,
      each: 'Each',
      bulk: 'Bulk',
      countInStock: 10,
      countInStockBulk: 10,
      notes: 'Sold Each',
      includes: '1',
    },
  ],
};

export default data;
